### ISSUE TITLE
It's not clear what constitutes a service

### ISSUE THREAD

**Issue by minglis** [ministryofjustice/technical-risk-measures#6]
When we are identifying services to record the risk on, how do we decide what is a service and what is a component in a service.

For example. If we have an oracle database that is core, and has it's own patching cycle etc, is that a row, or is it bound up with the EBS application that uses it?

If an app has multiple components that can be released independently and users would raise tickets against them for issues, is that a row?

Are the individual pieces in a microservices architecture rows, or are they just the service. 

We need to provide guidance in this so that the level of granularity is the same.

**Comment by jennyd** [comment]
Fixed by #16
